"""added relations

Revision ID: 3fb89b53c50c
Revises: a8575a28b753
Create Date: 2026-02-18 11:30:29.797767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb89b53c50c'
down_revision: Union[str, Sequence[str], None] = 'a8575a28b753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('user_uuid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'holdings', 'users', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('holdings', 'uuid')
    op.add_column('transactions', sa.Column('user_uuid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'users', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_column('transactions', 'uuid')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('transactions', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_uuid')
    op.add_column('holdings', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.drop_column('holdings', 'user_uuid')
    # ### end Alembic commands ###
