"""initial migration

Revision ID: a8575a28b753
Revises: 
Create Date: 2026-02-18 10:22:07.647474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8575a28b753'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('holdings_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('holdings_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.add_column('stockprices', sa.Column('curr_prices', sa.Float(), nullable=True))
    op.add_column('stockprices', sa.Column('max_prices_24', sa.Float(), nullable=True))
    op.add_column('stockprices', sa.Column('min_prices_24', sa.Float(), nullable=True))
    op.add_column('stockprices', sa.Column('max_prices_1', sa.Float(), nullable=True))
    op.add_column('stockprices', sa.Column('min_prices_1', sa.Float(), nullable=True))
    op.add_column('stockprices', sa.Column('prices', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('stockprices', sa.Column('times', postgresql.ARRAY(sa.Float()), nullable=True))
    op.create_unique_constraint(None, 'stockprices', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stockprices', type_='unique')
    op.drop_column('stockprices', 'times')
    op.drop_column('stockprices', 'prices')
    op.drop_column('stockprices', 'min_prices_1')
    op.drop_column('stockprices', 'max_prices_1')
    op.drop_column('stockprices', 'min_prices_24')
    op.drop_column('stockprices', 'max_prices_24')
    op.drop_column('stockprices', 'curr_prices')
    op.drop_table('transactions')
    op.drop_table('holdings')
    # ### end Alembic commands ###
